services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: lgtm-stack
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
      - '9090:9090'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - lgtm-data:/data
      - ./observability/prometheus.yml:/otel-lgtm/prometheus.yaml

volumes:
  postgres_data:
  lgtm-data:
